#!/bin/bash

# Version 2.1
# Author: Juanjo Salvador
# Website: http://juanjosalvador.github.io/
# Repo: https://github.com/JuanjoSalvador/CPacket

# Functions: standard, inputdir, help

function standard () { # no options
	IFS='
	'
		for i in * ; do
			if [ -d $i ] && [ ! -e "$i.cbz" ]; then
					echo "Procesando $i..."
					newName=`echo $i | tr " " '\ '`
					if [ $i != "$newName" ]; then
						$(mv $i $newName >> /dev/null) || echo "Ocurrió un error al procesar $i"
					fi
					packed=`echo $newName.cbz`
					$(zip $packed $newName/*.jpg >> /dev/null) || echo "Ocurrió un error al procesar $i"
					echo "$newName.cbz generado correctamente."
			else
				echo "$i no es un directorio, o ya ha sido procesado."
			fi
		done
}

function inputdir () { # -d
	IFS='
	'
	if [ -z $1 ]; then
			echo "Falta un directorio."
	else
		if [ -d $1 ] && [ ! -e "$1.cbz" ]; then
			for i in $1 ; do
				echo "Procesando $i..."
				newName=`echo $i | tr " " '\ '`
				if [ $i != "$newName" ]; then
					$(mv $i $newName >> /dev/null) || echo "Ocurrió un error al procesar $i"
				fi
				packed=`echo $newName.cbz`
				$(zip $packed $newName/*.jpg >> /dev/null) || echo "Ocurrió un error al procesar $i"
				echo "$newName.cbz generado correctamente."
			done
		else
			echo "$1 no es un directorio, o ya ha sido procesado."
		fi
	fi
}

function help () { # -help
	echo "USO DE CPACKET"
	echo "cpacket <opcion> <directorio>"
	echo " "
	echo "OPCIONES"
	echo "Sin opciones  Empaqueta recursivamente en CBZ el directorio actual."
	echo "-d            Empaqueta el directorio que le pasamos como argumento en CBZ."
	echo "-r            Empaqueta el directorio que le pasamos como argumento en CBZ, recursivamente."
	echo "--help        Muestra este menú de ayuda."
}

# Arguments

case "$1" in
	-d)
		inputdir "$2"
	  ;;
	--help)
	  help
		;;
	"")
	  standard
		;;
	*)
	 echo "Prueba con --help para ver ayuda."
esac
