#!/bin/bash

# Version 2.2
# Author: Juanjo Salvador
# Website: http://juanjosalvador.github.io/
# Repo: https://github.com/JuanjoSalvador/CPacket

# Functions: standard, recursive, inputdir, help

function standard () {
	dir="Directorio único"
  rec="Recursivo"
  help="Mostrar ayuda"

  boolean=`zenity --title "Text" \
  --text "Selecciona una opción" \
  --list --radiolist --column "" --column "" One "$dir" Two "$rec" Three "$help"`

  case "$boolean" in
    $dir)
      FILE=`zenity --file-selection --title="Selecciona un directorio" --directory`
      (cpacket -d "$FILE") 2>&1 | zenity --progress --title "Procesando" --text "Creando: $FILE.cbz" --pulsate --auto-close
			zenity --info --text "Finalizado."
      ;;
    $rec)
			FILE=`zenity --file-selection --title="Selecciona un directorio" --directory`
			(cpacket -r "$FILE") 2>&1 | zenity --progress --title "Procesando" --text "Creando: $FILE.cbz" --pulsate --auto-close
			zenity --info --text "Finalizado."
      ;;
    $help)
      echo "Has elegido Mostrar ayuda"
			zenity --info --text "En desarrollo"
      ;;
    *)
  esac
}

function recursive () { # -r
	IFS='
	'
	if [ -z $1 ]; then
			echo "Falta un directorio."
	else
		for i in $1/* ; do
			if [ -d $i ] && [ ! -e "$i.cbz" ]; then
					echo "Procesando $i..."
					newName=`echo $i | tr " " '\ '`
					if [ $i != "$newName" ]; then
						$(mv $i $newName >> /dev/null) || echo "Ocurrió un error al procesar $i"
					fi
					packed=`echo $newName.cbz`
					$(zip -q $packed $newName/*.jpg && echo "$newName.cbz generado correctamente.") || echo "Ocurrió un error al procesar $i"
			else
				echo "$i no es un directorio, o ya ha sido procesado."
			fi
		done
	fi
}

function inputdir () { # -d
	IFS='
	'
	if [ -z $1 ]; then
			echo "Falta un directorio."
	else
		if [ -d $1 ] && [ ! -e "$1.cbz" ]; then
			for i in $1 ; do
				echo "Procesando $i..."
				newName=`echo $i | tr " " '\ '`
				if [ $i != "$newName" ]; then
					$(mv $i $newName >> /dev/null) || echo "Ocurrió un error al procesar $i"
				fi
				packed=`echo $newName.cbz`
				$(zip -q $packed $newName/*.jpg && echo "$newName.cbz generado correctamente.") || echo "Ocurrió un error al procesar $i"
			done
		else
			echo "$1 no es un directorio, o ya ha sido procesado."
		fi
	fi
}

function help () { # -help
	echo "USO DE CPACKET"
	echo "cpacket <opcion> <directorio>"
	echo " "
	echo "OPCIONES"
	echo "Sin opciones  Empaqueta recursivamente en CBZ el directorio actual."
	echo "-d            Empaqueta el directorio que le pasamos como argumento en CBZ."
	echo "-r            Empaqueta el directorio que le pasamos como argumento en CBZ, recursivamente."
	echo "--help        Muestra este menú de ayuda."
}

# Arguments

case "$1" in
	-d)
		inputdir "$2"
	  ;;
	-r)
		recursive "$2"
	  ;;
	--help)
	  help
		;;
	"")
	  standard
		;;
	*)
	 echo "Prueba con --help para ver ayuda."
esac
