#!/bin/bash

# [Comicbook Packager] Installer
# Dependencies: zenity, zip, poppler-utils
# Version 2.3 for Debian/Ubuntu
# Author: Juanjo Salvador
# Twitter: @Linuxneitor
# Website: http://juanjosalvador.github.io/
# Repo: https://github.com/JuanjoSalvador/ComicbookPackager

dependencies=( "zenity" "zip" "pdfimages" )

	if [ "$EUID" -ne 0 ]; then
		echo "Necesita privilegios de superusuario. Ejecuta el instalador como sudo."
		exit
	else

		echo "Instalando Comicbook Packager..."
		echo "Comicbook Packager depende de zip, zenity y poppler-utils."

		for i in "${dependencies[@]}"
		do
			if [ -e "/usr/bin/$i" ]; then
				echo "El paquete $i está instalado."
			else
				if [ $i =! "pdfimages" ]; then
					apt-get install $i
				else
					apt-get install poppler-utils
				fi
			fi
			cp ./cbp /usr/local/bin
			chmod +x /usr/local/bin/cbp
		done
		echo "Finalizado"
	fi
